import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { motion } from 'framer-motion';
import movieDb from '@/lib/movieDb';

export default function Home({ movies = [] }) {
  return (
    <div className="container mx-auto">
      <div className="px-4 sm:px-6 py-12">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="grid grid-cols-1 sm:grid-cols-3 lg:grid-cols-5 gap-8">
          {movies.map(movie => (
            <Link href={`/${movie.id}`}>
              <motion.a
                key={movie.id}
                className="relative aspect-w-9 aspect-h-14 rounded-lg overflow-hidden cursor-pointer"
                whileHover={{ scale: 1.05, opacity: 0.8, zIndex: 1 }}
                whileTap={{ scale: 0.95 }}
              >
                <Image
                  src={`https://image.tmdb.org/t/p/original/${movie.poster_path}`}
                  layout="fill"
                />
              </motion.a>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  try {
    const { data } = await movieDb.get('/movie/popular');
    return {
      props: { movies: data?.results ?? [] },
    };
  } catch (e) {
    return {
      props: { movies: [] },
    };
  }
}
